### ISSUE TITLE
[Server] Проблемы с авторизацией

### ISSUE THREAD

**Issue by Veleri** [yehormonko/IMessanger#18]
Неправильная авторизация возникает:
- при подключения пользователя после перезагрузке сервера: с правильным паролем пользователь не авторизируется, с неправильным - авторизация успешна.

**Comment by yehorsyrin** [comment]
Ошибку не удалось воссоздать, нужно более подробное описание

**Comment by Veleri** [comment]
Тесткейс 1:
1.Запустить сервер
2.Подключить клиента к серверу
3.Отключить сервер
4.Убедится, что клиент потерял доступ к серверу
5.Включить сервер
6.Попытаться залогиниться

**Comment by yehorsyrin** [comment]
Ошибка больше не наблюдается
