### ISSUE TITLE
[Server] Ошибки регистрации пользователей

### ISSUE THREAD

**Issue by Veleri** [yehormonko/IMessanger#19]
При регистрации пользователя замечена ситуация, когда данные не вносятся в userList.xml

**Comment by yehorsyrin** [comment]
Нужно подробное описание ошибки, так как ее не удалось найти

**Comment by Veleri** [comment]
Ошибка наблюдается, после попытки сделать какого  - либо пользователя администратором путем редактирования файла userList.xml
