### ISSUE TITLE
[Add] Добавить интерфейсы

### ISSUE THREAD

**Issue by Veleri** [yehormonko/IMessanger#22]
Добавить интерфейсы для модели/представления/контроллера и, соответственно, имплементировать их.

**Comment by yehorsyrin** [comment]
На данный момент для того чтобы реализовать один класс, через который будет идти общение между, например моделью и контроллером сервера, нужно переделывать почти весь код того же сервера. Так же само и в клиенте. Потому что везде использовались экземпляры отдельных классов модели
