### ISSUE TITLE
[General] Разделить модель/контроллер

### ISSUE THREAD

**Issue by Veleri** [yehormonko/IMessanger#3]
Все методы касающиеся парсинга и обработки xml - файлов должны находится в модели.

**Comment by Veleri** [comment]
Доработка касается как сервера, так и клиента.

**Comment by Veleri** [comment]
Модель находится только на стороне сервера. Перенести модель клиента в серверную часть.

**Comment by SummertimeS4dness** [comment]
И как ее клиенту использовать?

**Comment by Veleri** [comment]
Импортировать классы модели сервера,
